### ISSUE TITLE
Player Model 1 (cell)

### ISSUE THREAD

**Issue by Medallyon** [Medallyon/evo-game#1]
By closing this issue, it means you have completed the following stages for **Player Model 1** (cell):

- [x] Modelling
  - [ ] 3D Model
  - [ ] Rigging
  - [ ] Skinning
  - [x] Textures
- [x] Animating
  - [x] Movement
  - [x] Death

**Comment by MichalisAntonas** [comment]
Implemented in fc0907029037ff3251bf727a90f9f9ae0210de2d. Animation is done inside Unity using the `RandomAxisRotator` script.
