### ISSUE TITLE
Item Model 1 (bacteria?)

### ISSUE THREAD

**Issue by Medallyon** [Medallyon/evo-game#4]
By closing this issue, it means you have completed the following stages for **Item Model 1** (bacteria?):

- [x] Modelling
  - [x] 3D Model
  - [ ] Rigging
  - [ ] Skinning
  - [x] Textures
- [x] Animating
  - [x] Movement

**Comment by MichalisAntonas** [comment]
Implemented in fc0907029037ff3251bf727a90f9f9ae0210de2d. Animation is done inside Unity using the `RandomAxisRotator` script.
